### ISSUE TITLE
KvantWall for HDRP

### ISSUE THREAD

**Issue by havocfire** [keijiro/KvantWall#4]
Hello, could you update KvantSwarmt and KvantWall for HDRP in Unity6?

**Comment by keijiro** [comment]
I'd recommend using VFX Graph instead. It's performant, versatile and easy-to-use. There is no advantage in this old solution.

**Comment by havocfire** [comment]
> I'd recommend using VFX Graph instead. It's performant, versatile and easy-to-use. There is no advantage in this old solution.

Could you do it with VFX Graph on small surface?
